version: '3'

services:

  pm1:
    image: ${MCS_IMAGE_NAME}
    shm_size: '512mb'
    hostname: ${PM1}
    container_name: ${PM1}
    volumes:
      - data1:/var/lib/columnstore/data1
      - storagemanager:/var/lib/columnstore/storagemanager
      - ${PWD}/sql:/tmp/sql
      - ${PWD}/bin/bootstrap_cs.sh:/usr/bin/bootstrap
    env_file:
      - .env
    ports:
      - 3307:3306

  xpd1:
    image: ${XPD_IMAGE_NAME}
    deploy:
    ulimits:
      memlock: -1
    hostname: ${XPD1}
    container_name: ${XPD1}
    volumes:
      - ${PWD}/bin/xpd_setup.sh:/usr/bin/xpd_setup
    env_file:
      - .env
    links:
      - "pm1"
    ports:
      - 3306:3306

volumes:
  data1:
  storagemanager:
